/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Item: typeof import('./src/components/Data/item.vue')['default']
    Item_two: typeof import('./src/components/Data/item_two.vue')['default']
    Item1: typeof import('./src/components/Data/item1.vue')['default']
    ItemFour: typeof import('./src/components/Data/item-four.vue')['default']
    ItemOne: typeof import('./src/components/Data/item-one.vue')['default']
    ItemThree: typeof import('./src/components/Data/item-three.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    LoginForm: typeof import('./src/components/Login/LoginForm.vue')['default']
    Map: typeof import('./src/components/Data/Map.vue')['default']
    RegisterForm: typeof import('./src/components/Login/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
